version: 2

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too noisy, low value for this project
  staticcheck:
    checks: ["all"]

issues:
  exclude-dirs:
    - _output
    - vendor
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
    # Exclude generated files
    - path: zz_generated
      linters:
        - staticcheck
        - unused
  max-issues-per-linter: 0
  max-same-issues: 0
