run:
  timeout: 5m
  skip-files:
    - "test/util/fake.go"  # Has k8s.io/apimachinery import compatibility issues with golangci-lint

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
    staticcheck:
      checks: ["all"]
