apiVersion: v1
kind: Pod
metadata:
  name: simple-test-pod
  namespace: default
spec:
  schedulerName: kubenexus-scheduler
  containers:
  - name: test
    image: busybox:latest
    command: ["sh", "-c", "echo 'Hello' && sleep 10"]
  restartPolicy: Never
