apiVersion: v1
kind: Pod
metadata:
  name: test-nginx-pod
  labels:
    app: test-nginx
spec:
  schedulerName: kubenexus-scheduler
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    ports:
    - containerPort: 80
